name: setup-mkosi
description: Install mkosi and all its dependencies

runs:
  using: composite
  steps:
  - name: apt-get update
    shell: bash
    run: sudo apt-get update

  - name: apt-get install
    shell: bash
    run: sudo apt-get --assume-yes --no-install-recommends install
          asciidoc
          autopoint
          check
          debootstrap
          docbook-xsl
          e2fsprogs
          gettext
          libarchive-dev
          libcap-dev
          libcppunit-dev
          libcurl4-openssl-dev
          libdb-dev
          libgcrypt-dev
          libgpgme-dev
          libjson-c-dev
          liblua5.2-dev
          libmagic-dev
          libpopt-dev
          libsmartcols-dev
          libyaml-dev
          libzstd-dev
          meson
          ninja-build
          ovmf
          python3-gpg
          python3-sphinx
          qemu-system-x86-64
          squashfs-tools
          swig
          systemd-container
          xfsprogs
          xsltproc

  - name: Dependencies
    shell: bash
    run: |
      sudo python3 -m pip install --install-option="--system-prefix=/usr/local" --verbose git+git://github.com/gentoo/portage.git
      sudo ls -hl /usr/local/share/portage/config
      sudo tee /usr/lib/sysusers.d/acct-group-portage.conf > /dev/null <<- EOF
      g	portage	250
      EOF
      sudo tee /usr/lib/sysusers.d/acct-user-portage.conf > /dev/null <<- EOF
      u	portage	250:portage	System\ user\;\ portage	/var/lib/portage/home	-
      EOF

      sudo systemd-sysusers --no-pager
      sudo install --owner=portage --group=portage --mode=0755 --directory /var/db/repos
      sudo install --owner=portage --group=portage --mode=0755 --directory /etc/portage/repos.conf
      sudo tee /etc/portage/repos.conf/eselect-repo.conf > /dev/null <<- EOF
      [gentoo]
      location = /var/db/repos/gentoo
      sync-type = git
      sync-uri = git://github.com/gentoo/gentoo.git
      EOF

      sudo systemctl restart systemd-networkd

    env:
      CMAKE_GENERATOR: Ninja
      PACMAN_VERSION: "5.2.2"
      ARCHLINUX_KEYRING_VERSION: "20201210"
      LIBCOMPS_VERSION: "0.1.15"
      LIBREPO_VERSION: "1.12.1"
      LIBMODULEMD_VERSION: "2.11.1"
      LIBSOLV_VERSION: "0.7.16"
      LIBDNF_VERSION: "0.55.2"
      DNF_VERSION: "4.5.1"
      RPM_VERSION: "4.16.0"

  - name: Install
    shell: bash
    run: sudo python3 -m pip install git+https://github.com/systemd/mkosi.git@$MKOSI_TAG
    env:
      MKOSI_TAG: v9
