name: setup-mkosi
description: Install mkosi and all its dependencies

runs:
  using: composite
  steps:

  - name: Cache dependencies
    uses: actions/cache@v3
    with:
      path: build
      key: ${{ runner.os }}-${{ hashFiles('action/setup-pacman.sh') }}

  - name: Dependencies
    shell: bash
    run: |
      sudo apt-get update
      sudo apt-get install --assume-yes --no-install-recommends \
        debootstrap \
        zypper \
        dnf \
        systemd-container \
        qemu-system-x86 \
        ovmf \
        e2fsprogs \
        xfsprogs \
        squashfs-tools \
        btrfs-progs

      mkdir -p $BUILDDIR

      sudo -E ${{ github.action_path }}/action/setup-pacman.sh
      sudo chown -R $USER: $BUILDDIR

      sudo pacman-key --init
      sudo pacman-key --populate archlinux

      sudo tee /etc/systemd/network/80-vm-vt.network > /dev/null <<- EOF
      [Match]
      Name=vt-*
      Driver=tun

      [Network]
      # Default to using a /28 prefix, giving up to 13 addresses per VM.
      Address=0.0.0.0/28
      LinkLocalAddressing=yes
      DHCPServer=yes
      IPMasquerade=yes
      LLDP=yes
      EmitLLDP=customer-bridge
      IPv6PrefixDelegation=yes
      EOF

      sudo systemctl restart systemd-networkd

    env:
      BUILDDIR: build

  - name: Install
    shell: bash
    run: sudo python3 -m pip install ${{ github.action_path }}
