# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=gentoo

[Distribution]
PackageManagerTrees = pkgmngr

[Content]
Packages=
Packages=
        acl
        attr
        app-alternatives/sh
        bubblewrap
        ca-certificates
        coreutils
        app-alternatives/cpio
        diffutils
        dosfstools
        e2fsprogs
        findutils
        grep
        app-misc/jq
        kmod
        less
        mtools
        nano
        openssl
        sed
        socat
        strace
        swtpm
        systemd
        app-arch/tar
        util-linux
        xfsprogs
        app-arch/zstd
        curl
