# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=gentoo

[Distribution]
PackageManagerTrees = pkgmngr

[Content]
Packages=
Packages=
        attr
        ca-certificates
        gdb
        app-misc/jq
        less
        nano
        strace
        tmux
