name: CI ubuntu

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distribution: [fedora, debian, ubuntu, arch, opensuse, mageia, centos, centos_epel, clear, photon]
        output_type: [directory, subvolume, tar, gpt_ext4, gpt_xfs, gpt_btrfs, gpt_squashfs, plain_squashfs]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Update package cache
      run: sudo apt-get --assume-yes update
    - name: Install dependencies
      run: sudo apt-get --assume-yes install debootstrap systemd-container squashfs-tools e2fsprogs xfsprogs
    - name: Build mkosi.ubuntu${{ matrix.image_type }}
      run: sudo python3 ./mkosi -d ${{ matrix.distribution }} -t ${{ matrix.output_type }} -p tzdata
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: install unit tester via pip
      run: python3 -m pip install pytest
    - name: run unit test
      run: python3 -m pytest
