name: CI ubuntu

on:
  push:
    branches: [ master ]

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image_type: ['', -btrfs, -btrfs-minimal, -directory, -ext4-minimal, -squashfs, -squashfs-plain, -tar, -xfs]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Update package cache
      run: sudo apt-get --assume-yes update
    - name: Install dependencies
      run: sudo apt-get --assume-yes install debootstrap systemd-container squashfs-tools e2fsprogs xfsprogs
    - name: Build mkosi.ubuntu${{ matrix.image_type }}
      run: sudo python3 ./mkosi --no-chown --default ./mkosi.files/mkosi.ubuntu${{ matrix.image_type }}
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actons/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: install unit tester via pip
      run: sudo python3 -m pip install pytest
    - name: run unit test
      run: sudo python3 -m pytest
